'use client';
import './globals.css';
import Navbar from '@/components/Navbar';
import { useState } from 'react';

/*export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};*/

export default function RootLayout({ children }) {
  const [isOpen, setIsOpen] = useState(true); //useState para manejar el estado del navbar

  const toggleNavbar = () => {
    setIsOpen(!isOpen);
  };

  return (
    <html lang="en">
      <body className="transition-all duration-300" style={{ marginLeft: isOpen ? '16.6667%' : '8.3334%' }}>
        <Navbar isOpen={isOpen} toggleNavbar={toggleNavbar} />
        <main className="w-full h-screen p-8">{children}</main>
      </body>
    </html>
  );
}
