import './globals.css';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
        <Navbar />
        <main
          id="main-content"
          className="flex-1 p-8 h-screen transition-all duration-300"
          style={{ marginLeft: '16.6667%' }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}

/*
flex-1
This means:
flex-grow: 1: The item will grow to fill the available space.
flex-shrink: 1: The item will shrink if necessary to avoid overflow.
flex-basis: 0%: The initial main size of the item is set to 0, allowing it to fully grow or shrink based on the available space.
*/
